CREATE TABLE air_quality_results (
    city VARCHAR(50),
    window TIMESTAMP,
    avg_temperature DOUBLE PRECISION,
    avg_aqi DOUBLE PRECISION,
    avg_co DOUBLE PRECISION,
    avg_no2 DOUBLE PRECISION,
    avg_o3 DOUBLE PRECISION,
    avg_so2 DOUBLE PRECISION,
    avg_pm2_5 DOUBLE PRECISION,
    avg_pm10 DOUBLE PRECISION,
    temp_aqi_corr DOUBLE PRECISION,
    temp_co_corr DOUBLE PRECISION,
    temp_no2_corr DOUBLE PRECISION,
    temp_o3_corr DOUBLE PRECISION,
    temp_so2_corr DOUBLE PRECISION,
    temp_pm2_5_corr DOUBLE PRECISION,
    temp_pm10_corr DOUBLE PRECISION,
    moderate_aqi_temp_threshold DOUBLE PRECISION,
        high_no2_temp_threshold DOU
